CREATE TABLE BlogPost (
  post_id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  views INT DEFAULT 0,
  content LONGTEXT
);


CREATE TABLE CalendarEvent ( 
  event_id INT AUTO_INCREMENT PRIMARY KEY, 
  event_title VARCHAR(255) NOT NULL, 
  start_time DATETIME NOT NULL, 
  end_time DATETIME NOT NULL, 
  event_text LONGTEXT, 
  event_type varchar(255) NOT NULL,
  creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE User (
  email VARCHAR(255) NOT NULL PRIMARY KEY,
  username VARCHAR(255) NOT NULL
);